name: supportsense-airflow

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - .env
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: "http://supportsense-airflow-apiserver:8080/execution/"
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
    AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
    AIRFLOW__CORE__AUTH_MANAGER: airflow.api_fastapi.auth.managers.simple.simple_auth_manager.SimpleAuthManager
    AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS: admin:admin
    AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
    AIRFLOW__API_AUTH__JWT_SECRET: ${AIRFLOW_JWT_SECRET}
    AIRFLOW__API_AUTH__JWT_ISSUER: supportsense-airflow
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:${POSTGRES_PASSWORD}@supportsense-postgres:5432/airflow
  user: "${AIRFLOW_UID}:0"
  extra_hosts:
    - "host.docker.internal:host-gateway"
  volumes:
    - ./dags:/opt/airflow/dags
    - ../:/opt/airflow/SupportSense
    - supportsense_airflow_logs:/opt/airflow/logs
  depends_on:
    supportsense-postgres:
      condition: service_healthy

services:

  supportsense-postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - supportsense_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow", "-d", "airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  supportsense-airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db migrate
    restart: "no"

#  supportsense-airflow-init:
#    <<: *airflow-common
#    entrypoint: /bin/bash
#    command:
#      - -c
#      - |
#        airflow db migrate
#        airflow users create \
#          --username admin \
#          --firstname SupportSense \
#          --lastname Admin \
#          --role Admin \
#          --email admin@supportsense.local \
#          --password "$AIRFLOW_ADMIN_PASSWORD" || true
#    restart: "no"

  supportsense-airflow-apiserver:
    <<: *airflow-common
    command: api-server
    ports:
      - "18080:8080"
    depends_on:
      supportsense-postgres:
        condition: service_healthy
      supportsense-airflow-init:
        condition: service_completed_successfully

  supportsense-airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      supportsense-postgres:
        condition: service_healthy
      supportsense-airflow-init:
        condition: service_completed_successfully

  supportsense-airflow-dag-processor:
    <<: *airflow-common
    command: dag-processor
    depends_on:
      supportsense-postgres:
        condition: service_healthy
      supportsense-airflow-init:
        condition: service_completed_successfully

  supportsense-airflow-triggerer:
    <<: *airflow-common
    command: triggerer
    depends_on:
      supportsense-postgres:
        condition: service_healthy
      supportsense-airflow-init:
        condition: service_completed_successfully

volumes:
  supportsense_airflow_logs:
    name: supportsense-airflow_supportsense_airflow_logs

  supportsense_postgres_data:
    name: supportsense-airflow_supportsense_postgres_data
